version: "3"

services:
  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=long120601
      - MYSQL_DATABASE=demo
    volumes:
      - dbdata:/var/lib/mysql
      - ./demo.sql:/docker-entrypoint-initdb.sql
  web:
    image: maven-docker
    depends_on:
      - db
    ports:
    - 8081:8080
volumes:
  dbdata: